@startuml
User -> UI: deleteHabit(ID)
UI -> Logic: deleteHabit(ID)
Logic -> DataAccess: deleteHabit(ID)
DataAccess -> DB: Delete Habit
DB --> DataAccess: success
DataAccess --> Logic: success
Logic --> UI: success
UI -> UI: deleteHabitView(ID)
@enduml