@startuml
User -> UI: Edit habit
UI -> Logic: editHabit(attr)
Logic -> DataAccess: editHabit(attr, table)
DataAccess -> DB: Update Habit attr
DB --> DataAccess: success
DataAccess --> Logic: success
Logic --> UI: success
UI -> UI: updateHabitView(attr)
@enduml
